export default {
  Category: [
    {
      id: '1',
      category: 'Nike',
    },
    {
      id: '2',
      category: 'adidas',
    },
    {
      id: '3',
      category: 'FILA',
    },
    {
      id: '4',
      category: 'Supreme',
    },
    {
      id: '5',
      category: 'Champion',
    },
    {
      id: '6',
      category: 'Under Armour',
    },
  ],
  Product: [
    {
      id: '1',
      categoryid: '1',
      product: 'Nike Elemental',
      image: require('./BbAllAssets/Images/1.png'),
      dis:
        'Its durable design features 2 zippered compartments to keep your stuff secure. Padded shoulder straps are adjustable for comfort and the fit you want.',
      added: 0,
      bgcolor: '#FAD8D8',
      rating: '4.9',
      price: '29',
    },
    {
      id: '2',
      categoryid: '1',
      product: 'Nike Future Pro',
      image: require('./BbAllAssets/Images/2.png'),
      dis:
        'A spacious interior and multiple pockets outside keep your stuff secure.',
      added: 0,
      bgcolor: '#C4E0F0',
      rating: '4.7',
      price: '50',
    },
    {
      id: '3',
      categoryid: '1',
      product: 'Nike Brasilia Varsity',
      image: require('./BbAllAssets/Images/3.png'),
      dis:
        'It includes a laptop sleeve, multiple zippered compartments, pockets and a drink pouch on the side.',
      added: 0,
      bgcolor: '#C4C4C4',
      rating: '4.8',
      price: '32',
    },
    {
      id: '4',
      categoryid: '1',
      product: 'Nike Just Do It',
      image: require('./BbAllAssets/Images/4.png'),
      dis:
        'The Nike Just Do It Backpack (Mini) features a main compartment and padded shoulder straps for ample storage and comfortable carrying.',
      added: 0,
      bgcolor: '#DCFFBD',
      rating: '4.9',
      price: '26',
    },
    {
      id: '5',
      categoryid: '1',
      product: 'Nike Hayward 2.0',
      image: require('./BbAllAssets/Images/5.png'),
      dis:
        'The Nike Hayward 2.0 Backpack combines simplicity and functionality with its sleek design and easy-to-access compartments.',
      added: 0,
      bgcolor: '#B6B6B6',
      rating: '4.6',
      price: '65',
    },
    {
      id: '6',
      categoryid: '2',
      product: 'adidas MODERN BACKPACK',
      image: require('./BbAllAssets/Images/6.png'),
      dis: 'CONTEMPORARY BACKPACK GIVES THE GREEN LIGHT FOR HIGH-TECH TRAVELS.',
      added: 0,
      bgcolor: '#E5D8AF',
      rating: '4.4',
      price: '50',
    },
    {
      id: '7',
      categoryid: '2',
      product: 'adidas NATIONAL 3-STRIPES BACKPACK',
      image: require('./BbAllAssets/Images/7.png'),
      dis:
        'AN EVERYDAY BACKPACK WITH SPORTY ADIDAS BRANDING AND CLASSIC CAMOUFLAGE.',
      added: 0,
      bgcolor: '#FFDFC0',
      rating: '4.5',
      price: '28',
    },
    {
      id: '8',
      categoryid: '2',
      product: 'adidas ADICOLOR CLASSIC BACKPACK',
      image: require('./BbAllAssets/Images/8.png'),
      dis: 'A SIMPLE BACKPACK TO CARRY EVERYDAY ESSENTIALS.',
      added: 0,
      bgcolor: '#ECECEC',
      rating: '4.3',
      price: '20',
    },
    {
      id: '9',
      categoryid: '2',
      product: 'adidas LEAGUE 3-STRIPES BACKPACK',
      image: require('./BbAllAssets/Images/9.png'),
      dis: 'A STURDY BACKPACK FOR EVERYDAY WEAR.',
      added: 0,
      bgcolor: '#D1CFCE',
      rating: '4.7',
      price: '28',
    },
    {
      id: '10',
      categoryid: '2',
      product: 'adidas NATIONAL FESTIVAL CROSSBODY BAG',
      image: require('./BbAllAssets/Images/10.png'),
      dis: 'THE DESIGNATED CROSSBODY BAG FOR ALL YOUR ACTIVITIES.',
      added: 0,
      bgcolor: '#FFC78E',
      rating: '4.5',
      price: '25',
    },
    {
      id: '11',
      categoryid: '3',
      product: 'Black Nylon Backpack With Logo',
      image: require('./BbAllAssets/Images/11.png'),
      dis:
        'Adjustable shoulder straps. Zip closure. Front logo. Outer zip pocket. Inner zip pocket. Front logo. Dimensions: 42 cm x 36 cm x 12 cm. 100% polyester. Color: black',
      added: 0,
      bgcolor: '#E5E5E5',
      rating: '4.9',
      price: '28',
    },
    {
      id: '12',
      categoryid: '3',
      product: 'Blue Malmö Mini Backpack',
      image: require('./BbAllAssets/Images/12.png'),
      dis:
        'Height: 34cm Width: 26cm Depth: 11cm. Double adjustable shoulder straps. Single top handle. Zip closure. Front logo detail. One front zip pocket. Internal patch pockets. Color: blue',
      added: 0,
      bgcolor: '#DCECF9',
      rating: '4.6',
      price: '20',
    },
    {
      id: '13',
      categoryid: '3',
      product: 'Green Verdon Dusty Olive / White Backpack',
      image: require('./BbAllAssets/Images/13.png'),
      dis:
        'The Verdon backpack comes with a frontal logo print in a contrasting color. Other features include padded back panel, a top handle and zip closure for both front and main pockets. Adjustable padded shoulder straps - 100% polyester. Color: green',
      added: 0,
      bgcolor: '#F0DBAA',
      rating: '4.4',
      price: '28',
    },
    {
      id: '14',
      categoryid: '3',
      product: 'Black Logo Backpack',
      image: require('./BbAllAssets/Images/14.png'),
      dis:
        'Dimensions: Width: 36cm, Height: 42cm, Depth: 12cm 100% Polyester. Made in Vietnam. Color: black',
      added: 0,
      bgcolor: '#C0C0C0',
      rating: '4.5',
      price: '25',
    },
    {
      id: '15',
      categoryid: '3',
      product: 'Chest Bag With Logo Unisex Black',
      image: require('./BbAllAssets/Images/15.png'),
      dis:
        'Black chest bag from Fila. Zip fastening. Zip pocket and logo print on the front. Trimmed with textured fabric. Adjustable shoulder straps. One compartment inside. Color: black',
      added: 0,
      bgcolor: '#D4D4D4',
      rating: '4.3',
      price: '32',
    },
    {
      id: '16',
      categoryid: '4',
      product: 'Louis Vuitton x Supreme Christopher Backpack',
      image: require('./BbAllAssets/Images/16.png'),
      dis:
        'The Louis Vuitton x Supreme Christopher backpack in red is a structured bag dripping in style. It comes with adjustable leather shoulder straps, a leather top handle, flap opening, press stud and drawstring closure as well as several pockets inside.',
      added: 0,
      bgcolor: '#F49898',
      rating: '4.7',
      price: '28',
    },
    {
      id: '17',
      categoryid: '4',
      product: 'Supreme Backpack Backpack (FW20) Dark Red',
      image: require('./BbAllAssets/Images/17.png'),
      dis: 'STYLE: SUP-BADRD, SEASON: FW20, COLOR: DARK RED.',
      added: 0,
      bgcolor: '#FFB3B3',
      rating: '4.5',
      price: '20',
    },
    {
      id: '18',
      categoryid: '4',
      product: 'Supreme Backpack (SS20) Blue Chocolate Chip Camo',
      image: require('./BbAllAssets/Images/18.png'),
      dis:
        'The SS20 Backpack was released in four colors and features Cordura fabric, PVC coated meshing, and a 3M reflective Supreme Logo.',
      added: 0,
      bgcolor: '#BECDD5',
      rating: '4.9',
      price: '28',
    },
    {
      id: '19',
      categoryid: '4',
      product: 'Supreme Backpack (FW20) Leopard',
      image: require('./BbAllAssets/Images/19.png'),
      dis:
        "This Leopard print Backpack released as a part of the Supreme's Fall/Winter 2020 Week 1 drop alongside three other backpack colorways.",
      added: 0,
      bgcolor: '#E5D48E',
      rating: '4.6',
      price: '25',
    },
    {
      id: '20',
      categoryid: '4',
      product: 'Supreme 3M Reflective Repeat Backpack Black',
      image: require('./BbAllAssets/Images/20.png'),
      dis:
        'Supreme 3M Reflective Repeat Backpack Color: Red Material: Parachute',
      added: 0,
      bgcolor: '#DAD7C9',
      rating: '4.4',
      price: '32',
    },
    {
      id: '21',
      categoryid: '5',
      product: "Champion Men's Top Load Backpack",
      image: require('./BbAllAssets/Images/21.png'),
      dis: '82% Polyester/10% Nylon/8% Spandex; 2nd: 100% Polyester',
      added: 0,
      bgcolor: '#E4E4E4',
      rating: '4.5',
      price: '28',
    },
    {
      id: '22',
      categoryid: '5',
      product: "Champion Men's Manuscript Backpack, green, One size",
      image: require('./BbAllAssets/Images/22.png'),
      dis:
        'Large main compartment and internal flat zip pocket, Two internal flat zip pocket and two internal stretch mesh pockets',
      added: 0,
      bgcolor: '#D1C8A0',
      rating: '4.3',
      price: '20',
    },
    {
      id: '23',
      categoryid: '5',
      product: "Champion Kids' Youth Supercize Backpack",
      image: require('./BbAllAssets/Images/23.png'),
      dis:
        'One main compartment and interior padded laptop sleeve, Padded strap, back and bottom panels',
      added: 0,
      bgcolor: '#E9D2CD',
      rating: '4.7',
      price: '28',
    },
    {
      id: '24',
      categoryid: '5',
      product: 'Champion Franchise Backpack, Grey, One Size',
      image: require('./BbAllAssets/Images/24.png'),
      dis:
        'One large main compartment with slip laptop sleeve, Front zip pocket with internal organizer.',
      added: 0,
      bgcolor: '#C8C8C8',
      rating: '4.5',
      price: '25',
    },
    {
      id: '25',
      categoryid: '5',
      product: "Champion Men's Supercize Backpack",
      image: require('./BbAllAssets/Images/25.png'),
      dis:
        'One main compartment with a laptop compartment, Two exterior orangizer pocket and carry handle',
      added: 0,
      bgcolor: '#C6CFF5',
      rating: '4.9',
      price: '32',
    },
    {
      id: '26',
      categoryid: '6',
      product: 'Under Armour Hustle Backpack',
      image: require('./BbAllAssets/Images/26.png'),
      dis:
        'Soft-lined laptop sleeve—holds up to 15" MacBook Pro or similarly sized laptop, Water-repellent front valuables pocket to keep your stuff safe.',
      added: 0,
      bgcolor: '#B9B9B9',
      rating: '4.6',
      price: '28',
    },
    {
      id: '27',
      categoryid: '6',
      product: 'Under Armour Adult Hustle 4.0 Backpack',
      image: require('./BbAllAssets/Images/27.png'),
      dis:
        'WATER-RESISTANT & DURABLE: UA Storm technology delivers an element-battling, highly water-resistant finish to keep your stuff dry. Tough, abrasion-resistant bottom panel.',
      added: 0,
      bgcolor: '#C6C7C8',
      rating: '4.7',
      price: '25',
    },
    {
      id: '28',
      categoryid: '6',
      product: 'Under Armour Adult Loudon Backpack',
      image: require('./BbAllAssets/Images/28.png'),
      dis: 'UA Storm technology repels water without sacrificing breathability',
      added: 0,
      bgcolor: '#EEE0C0',
      rating: '4.5',
      price: '32',
    },
    {
      id: '29',
      categoryid: '6',
      product: "Under Armour Men's Yard Baseball Backpack",
      image: require('./BbAllAssets/Images/29.png'),
      dis:
        'Foam padded back panel for enhanced comfort & breathability, 100% Polyester, Machine Wash',
      added: 0,
      bgcolor: '#BEC2D3',
      rating: '4.9',
      price: '28',
    },
    {
      id: '30',
      categoryid: '6',
      product: 'Under Armour Halftime Backpack',
      image: require('./BbAllAssets/Images/30.png'),
      dis:
        'Padded back panel & adjustable, ergonomically shaped straps for more comfortable carry',
      added: 0,
      bgcolor: '#BEBEBE',
      rating: '4.6',
      price: '20',
    },
  ],
  Popular: [
    {
      id: '1',
      categoryid: '1',
      product: 'Nike Elemental',
      image: require('./BbAllAssets/Images/1.png'),
      dis:
        'Its durable design features 2 zippered compartments to keep your stuff secure. Padded shoulder straps are adjustable for comfort and the fit you want.',
      added: 0,
      bgcolor: '#FAD8D8',
      rating: '4.9',
      price: '29',
    },
    {
      id: '5',
      categoryid: '1',
      product: 'Nike Hayward 2.0',
      image: require('./BbAllAssets/Images/5.png'),
      dis:
        'The Nike Hayward 2.0 Backpack combines simplicity and functionality with its sleek design and easy-to-access compartments.',
      added: 0,
      bgcolor: '#B6B6B6',
      rating: '4.6',
      price: '65',
    },
    {
      id: '7',
      categoryid: '2',
      product: 'adidas NATIONAL 3-STRIPES BACKPACK',
      image: require('./BbAllAssets/Images/7.png'),
      dis:
        'AN EVERYDAY BACKPACK WITH SPORTY ADIDAS BRANDING AND CLASSIC CAMOUFLAGE.',
      added: 0,
      bgcolor: '#FFDFC0',
      rating: '4.5',
      price: '28',
    },
    {
      id: '27',
      categoryid: '6',
      product: 'Under Armour Adult Hustle 4.0 Backpack',
      image: require('./BbAllAssets/Images/27.png'),
      dis:
        'WATER-RESISTANT & DURABLE: UA Storm technology delivers an element-battling, highly water-resistant finish to keep your stuff dry. Tough, abrasion-resistant bottom panel.',
      added: 0,
      bgcolor: '#C6C7C8',
      rating: '4.7',
      price: '25',
    },
    {
      id: '23',
      categoryid: '5',
      product: "Champion Kids' Youth Supercize Backpack",
      image: require('./BbAllAssets/Images/23.png'),
      dis:
        'One main compartment and interior padded laptop sleeve, Padded strap, back and bottom panels',
      added: 0,
      bgcolor: '#E9D2CD',
      rating: '4.7',
      price: '28',
    },
    {
      id: '21',
      categoryid: '5',
      product: "Champion Men's Top Load Backpack",
      image: require('./BbAllAssets/Images/21.png'),
      dis: '82% Polyester/10% Nylon/8% Spandex; 2nd: 100% Polyester',
      added: 0,
      bgcolor: '#E4E4E4',
      rating: '4.5',
      price: '28',
    },
  ],
};
