export default {
  category: [
    {
      id: '1',
      Categoryname: 'perfume',
      iconwhite: require('./YgAllAssets/Images/perfume.png'),
      iconBrown: require('./YgAllAssets/Images/perfume1.png'),
    },
    {
      id: '2',
      Categoryname: 'nail polish',
      iconwhite: require('./YgAllAssets/Images/nail-polish.png'),
      iconBrown: require('./YgAllAssets/Images/nail-polish1.png'),
    },
    {
      id: '3',
      Categoryname: 'lipstick',
      iconwhite: require('./YgAllAssets/Images/lipstick.png'),
      iconBrown: require('./YgAllAssets/Images/lipstick1.png'),
    },
    {
      id: '4',
      Categoryname: 'face powder',
      iconwhite: require('./YgAllAssets/Images/powder.png'),
      iconBrown: require('./YgAllAssets/Images/powder1.png'),
    },
    {
      id: '5',
      Categoryname: 'beauty cream',
      iconwhite: require('./YgAllAssets/Images/creams.png'),
      iconBrown: require('./YgAllAssets/Images/creams1.png'),
    },
  ],
  product: [
    {
      id: '1',
      categoryid: '1',
      productname: 'Jimmy Choo Signature',
      weight: '75ml',
      types: 'perfume',
      images: require('./YgAllAssets/Images/JimmyChoo1.png'),
      price: '24',
      discription:
        'Jimmy Choo Eau de Parfum is an effortlessly glamorous scent that blends warm, rich and sensual notes',
    },
    {
      id: '2',
      categoryid: '1',
      productname: "Jimmy Choo L'eau",
      weight: '80ml',
      types: 'perfume',
      images: require('./YgAllAssets/Images/JimmyChoo2.png'),
      price: '18',
      discription:
        "Jimmy Choo L'Eau is a delicate fragrance evocating free-spirited, audacious, and fun moments of life",
    },
    {
      id: '3',
      categoryid: '1',
      productname: 'Black Orchid Parfum',
      weight: '70ml',
      types: 'perfume',
      images: require('./YgAllAssets/Images/TomFord1.png'),
      price: '22',
      discription:
        'In this new olfactive journey, ylang-ylang is amplified while rum absolute and black plum become even more pronounced, augmenting the sensuality of TOM FORD‘s original perfume',
    },
    {
      id: '4',
      categoryid: '1',
      productname: 'MÉTALLIQUE',
      weight: '90ml',
      types: 'perfume',
      images: require('./YgAllAssets/Images/TomFord2.png'),
      price: '15',
      discription:
        ':This floral scent is a metallic sheath, collided with crisp vert de bergamot and pink peppercorn.  ',
    },
    {
      id: '5',
      categoryid: '1',
      productname: 'Fucking Fabulous',
      weight: '85ml',
      types: 'perfume',
      images: require('./YgAllAssets/Images/TomFord3.png'),
      price: '26',
      discription:
        'This iconoclastic leather perfume is spicy, warm, and decadent. A gourmand almond and iris heart imbue textural richness to the luscious leather intensified by floral orris accord.',
    },
    {
      id: '6',
      categoryid: '1',
      productname: 'euphoria',
      weight: '90ml',
      types: 'perfume',
      images: require('./YgAllAssets/Images/CalvinKlein1.png'),
      price: '18',
      discription:
        'Euphoria is about sexiness, fantasy, and being captivating. Sexy and sensual, euphoria speaks to the woman who has the urge to break free from everyday life - to provocatively be part of an exciting world filled with pleasure,',
    },
    {
      id: '7',
      categoryid: '1',
      productname: 'ETERNITY',
      weight: '75ml',
      types: 'perfume',
      images: require('./YgAllAssets/Images/CalvinKlein2.png'),
      price: '12',
      discription:
        'inspired by the ideal of lasting love and intimacy, is a romantic floral fragrance. This harmonious blend of both classic and contemporary scents is a perfect combination,',
    },
    {
      id: '8',
      categoryid: '2',
      productname: 'take the espresso',
      weight: '25ml',
      types: 'nail polish',
      images: require('./YgAllAssets/Images/Essie1.png'),
      price: '18',
      discription:
        "a regular coffee doesn't cut it - get a burst of energy in this blackened dark chocolate brown quick dry nail polish",
    },
    {
      id: '9',
      categoryid: '2',
      productname: 'love at frost sight',
      weight: '19ml',
      types: 'nail polish',
      images: require('./YgAllAssets/Images/Essie2.png'),
      price: '15',
      discription:
        'at first glance, butterflies will flutter and your heart will be a glow in this baby blue nail polish brimming with glistening gold pearl',
    },
    {
      id: '10',
      categoryid: '2',
      productname: 'I Cannoli Wear',
      weight: '20ml',
      types: 'nail polish',
      images: require('./YgAllAssets/Images/opi1.png'),
      price: '11',
      discription:
        'Nail lacquer is the original nail polish formula that reinvented quality nail color, your top choice if you enjoy updating your manicure weekly. Show your OPI love with this pale gray shade of nail polish.',
    },
    {
      id: '11',
      categoryid: '2',
      productname: 'Maintaining My Sand Ity',
      weight: '15ml',
      types: 'nail polish',
      images: require('./YgAllAssets/Images/opi2.png'),
      price: '20',
      discription:
        "I'm crazy for this sandy beige long-wear nail polish...in a good way! Lose your mind over this sandy shade that shines.",
    },
    // {
    //   id: '12',
    //   categoryid: '2',
    //   productname: 'Machu Peach U',
    //   weight: '20ml',
    //   types: 'nail polish',
    //   images: require('./YgAllAssets/Images/opi3.png'),
    //   price: '30',
    //   discription:
    //     'Nail lacquer is the original nail polish formula that reinvented quality nail color, your top choice if you enjoy updating your manicure weekly',
    // },
    {
      id: '13',
      categoryid: '2',
      productname: 'Absolute Black',
      weight: '12ml',
      types: 'nail polish',
      images: require('./YgAllAssets/Images/jinsoon1.png'),
      price: '29',
      discription:
        'Rich, shiny black with lustrous cream finish. JINsoon Absolute Black is both a color and a fashion statement.',
    },
    {
      id: '14',
      categoryid: '2',
      productname: 'BIRDIE',
      weight: '15ml',
      types: 'nail polish',
      images: require('./YgAllAssets/Images/jinsoon2.png'),
      price: '18',
      discription:
        'This light purple lavender is a flattering accompaniment to all of your pastel favorites from the JINsoon line.',
    },
    {
      id: '15',
      categoryid: '2',
      productname: 'Austin',
      weight: '25ml',
      types: 'nail polish',
      images: require('./YgAllAssets/Images/Tenoverten1.png'),
      price: '29',
      discription:
        'This long-lasting lacquer delivers saturated, streak-free nail color without any expense to your overall nail health',
    },
    {
      id: '16',
      categoryid: '2',
      productname: 'AMBER',
      weight: '18ml',
      types: 'nail polish',
      images: require('./YgAllAssets/Images/Tenoverten2.png'),
      price: '24',
      discription:
        'does not contain: dibutyl phthalate (dbp), toluene, formaldehyde, formaldehyde resin, camphor, ethyl tosylamide, xylene, triphenyl phosphate (tphp)',
    },
    {
      id: '17',
      categoryid: '3',
      productname: 'AUDACIOUS SHEER MATTE LIPSTICK',
      weight: '5ml',
      types: 'lipstick',
      images: require('./YgAllAssets/Images/nars1.png'),
      price: '25',
      discription:
        'Introducing the cult-favorite sensorial formula, now with a soft-focus finish. Each swipe delivers delicate color with medium-sheer coverage and a petal-soft powder finish',
    },
    {
      id: '18',
      categoryid: '3',
      productname: 'AUDACIOUS LIPSTICK',
      weight: '7ml',
      types: 'lipstick',
      images: require('./YgAllAssets/Images/nars2.png'),
      price: '27',
      discription:
        'A muse, bouche. Four new shades of the cult-favorite luxury satin lip formula, named for the most inspiring women in François’ life: his mother, Claudette Augustine; and grandmothers, Léa and Ginette',
    },
    {
      id: '19',
      categoryid: '3',
      productname: 'French KissKiss',
      weight: '6ml',
      types: 'lipstick',
      images: require('./YgAllAssets/Images/guerlain1.png'),
      price: '14',
      discription:
        'he KissKiss routine: 1. Apply Liplift before lipstick and slightly beyond the lip contour, then blend in with the fingertips.',
    },
    {
      id: '20',
      categoryid: '3',
      productname: 'HYDRATING & PLUMPING TINTED LIP BALM',
      weight: '5ml',
      types: 'lipstick',
      images: require('./YgAllAssets/Images/guerlain2.png'),
      price: '24',
      discription:
        'Roselip nude colour before bed for soft and hydrated lips in the morningThe daily beauty booster: Apply KissKiss Roselip on the lips,',
    },
    {
      id: '21',
      categoryid: '3',
      productname: 'SHAPING CREAM LIP COLOUR',
      weight: '8ml',
      types: 'lipstick',
      images: require('./YgAllAssets/Images/guerlain3.png'),
      price: '22',
      discription:
        'surprises us once again by slipping into a precious and graceful little black dress. Its understated case shows off infinitely elegant curves',
    },
    {
      id: '22',
      categoryid: '4',
      productname: 'Matte Radiance Baked Powder',
      weight: '20gm',
      types: 'face powder',
      images: require('./YgAllAssets/Images/Laura1.png'),
      price: '20',
      discription:
        'Ultra-smooth baked face powder that provides natural colour with soft matte radiance',
    },
    {
      id: '23',
      categoryid: '4',
      productname: 'Blush Color Infusion',
      weight: '15gm',
      types: 'face powder',
      images: require('./YgAllAssets/Images/Laura2.png'),
      price: '28',
      discription:
        'Long lasting, sheer powder blush provides 10 hours of buildable, natural-looking cheek color for all skin tones.',
    },
    {
      id: '24',
      categoryid: '4',
      productname: 'Secret Concealer',
      weight: '25gm',
      types: 'face powder',
      images: require('./YgAllAssets/Images/Laura3.png'),
      price: '18',
      discription:
        "Laura's most universal under eye concealer offers medium coverage to correct dark circles and other imperfections,",
    },
    {
      id: '25',
      categoryid: '4',
      productname: 'Translucent Loose Setting Powde',
      weight: '20gm',
      types: 'face powder',
      images: require('./YgAllAssets/Images/Laura4.png'),
      price: '14',
      discription:
        'The #1 setting powder* sets makeup for 16 hours with a matte finish',
    },
    {
      id: '26',
      categoryid: '4',
      productname: 'MINERALIZE SKINFINISH',
      weight: '15gm',
      types: 'face powder',
      images: require('./YgAllAssets/Images/MAC2.png'),
      price: '19',
      discription:
        'a luxurious powder with m·a·c multi-mineral complex that adds highlights to the face and body.',
    },
    {
      id: '27',
      categoryid: '4',
      productname: 'Blot Powder Pressed',
      weight: '25gm',
      types: 'face powder',
      images: require('./YgAllAssets/Images/MAC3.png'),
      price: '29',
      discription:
        've been using this since i was a sophmore in highschool which is about 12 years ago.',
    },
    {
      id: '28',
      categoryid: '4',
      productname: 'Matte Sheer Pressed Powder',
      weight: '20gm',
      types: 'face powder',
      images: require('./YgAllAssets/Images/MAC4.png'),
      price: '23',
      discription:
        'I really like this. It lasts me for ages too. Alas I had forgotten to take it to work one day and was going out so purchased',
    },
    {
      id: '29',
      categoryid: '5',
      productname: 'Rosy Tone Moisturizer for Mature, Dull Skin',
      weight: '25ml',
      types: 'beauty cream',
      images: require('./YgAllAssets/Images/cream1.png'),
      price: '30',
      discription:
        "Rosy Tone Moisturizer is a daily face cream for mature, dull skin. This moisturizer for mature skin is formulated with Imperial Peony Extracts and LHA to gently exfoliate dull, sallow skin and revive skin's natural rosy tone.",
    },
    {
      id: '30',
      categoryid: '5',
      productname: 'Triple Power Anti-Aging Moisturizer',
      weight: '19ml',
      types: 'beauty cream',
      images: require('./YgAllAssets/Images/cream2.png'),
      price: '15',
      discription:
        'Revitalift Triple Power Daily Face Moisturizer, is an anti-aging moisturizer formulated with 3 of the top proven anti-aging ingredients: Pro-Retinol, Vitamin C and Hyaluronic Acid to visibly reduce wrinkles, firm and brighten skin',
    },
    {
      id: '31',
      categoryid: '5',
      productname: 'Moisturizer Fragrance Free',
      weight: '20ml',
      types: 'beauty cream',
      images: require('./YgAllAssets/Images/cream3.png'),
      price: '13',
      discription:
        '-aging moisturizer with Pro-Retinol, a stabilized retinol derivative that works alongside other ingredients in this formula to visibly reduce wrinkles and firm skin. Our face moisturizer also features Centella Asiata,',
    },
    {
      id: '32',
      categoryid: '5',
      productname: 'hydra beauty crème',
      weight: '15ml',
      types: 'beauty cream',
      images: require('./YgAllAssets/Images/CHANEL1.png'),
      price: '18',
      discription:
        'With its unique ability to bloom in the winter, the camellia blossom holds the secret to optimal hydration. CHANEL Research harnessed this power in exclusive Camellia Alba PFA',
    },
    {
      id: '33',
      categoryid: '5',
      productname: 'hydra beauty micro crème',
      weight: '20ml',
      types: 'beauty cream',
      images: require('./YgAllAssets/Images/CHANEL2.png'),
      price: '23',
      discription:
        'This moisturizer delivers a revolutionary infusion of 24-hour continuous hydration*. The water-light texture glides on with a sensorial burst of freshness and then transforms into the comfort of a cream',
    },
    {
      id: '34',
      categoryid: '5',
      productname: 'hydra beauty crème riche',
      weight: '12ml',
      types: 'beauty cream',
      images: require('./YgAllAssets/Images/CHANEL3.png'),
      price: '26',
      discription:
        'With its unique ability to bloom in the winter, the camellia blossom holds the secret to optimal hydration.',
    },
  ],
};
